FROM nginx:stable

ENV VIRTUAL_HOST="parjoehlerhof.it,www.parjoehlerhof.it"
ENV LETSENCRYPT_HOST="parjoehlerhof.it,www.parjoehlerhof.it"
ENV LETSENCRYPT_EMAIL="simonmulser@gmail.com"

COPY nginx.conf /etc/nginx/nginx.conf
